#!/bin/sh
# File generated by ocamlbuild

cd /home/xiaohe/workspace/monpoly-m

rm -f src/MFOTL.cmi
rm -f src/MFOTL.cmo
rm -f src/algorithm.cmi
rm -f src/algorithm.cmo
rm -f src/db.cmi
rm -f src/db.cmo
rm -f src/dllist.cmi
rm -f src/dllist.cmo
rm -f src/filter_empty_tp.cmi
rm -f src/filter_empty_tp.cmo
rm -f src/filter_rel.cmi
rm -f src/filter_rel.cmo
rm -f src/log.cmi
rm -f src/log.cmo
rm -f src/log_lexer.cmi
rm -f src/log_lexer.cmo
rm -f src/log_lexer.ml
rm -f src/log_parser.cmi
rm -f src/log_parser.cmo
rm -f src/log_parser.ml
rm -f src/log_parser.mli
rm -f src/misc.cmi
rm -f src/misc.cmo
rm -f src/monpoly.a
rm -f src/mqueue.cmi
rm -f src/mqueue.cmo
rm -f src/perf.cmi
rm -f src/perf.cmo
rm -f src/predicate.cmi
rm -f src/predicate.cmo
rm -f src/relation.cmi
rm -f src/relation.cmo
rm -f src/sliding.cmi
rm -f src/sliding.cmo
rm -f src/table.cmi
rm -f src/table.cmo
rm -f src/tuple.cmi
rm -f src/tuple.cmo
rm -f src/version.o
rm -f tools/mfotl2sql.o
rm -f tools/table2log.o
# Also clean the script itself
rm -f /home/xiaohe/workspace/monpoly-m/_build/sanitize.sh
